# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-HDFC
version:      v0.12.0
version_from: lib/Finance/Bank/HDFC.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    LWP::UserAgent:                0
    Readonly:                      0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
